apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-rollout-application
  namespace: argo-rollouts
spec:
  project: default

  source:
    repoURL: https://github.com/TejaJanakiRam/DevOpsArgoCD
    targetRevision: HEAD
    path: rollout
  destination: 
    server: https://kubernetes.default.svc
    namespace: rollouts-demo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true